#!/bin/bash

cmd=git

if [ -z "$ALL_HOME" ]; then
  initial=${PWD%%/};
else
  initial=${ALL_HOME%%/};
fi

cd $initial;

if [ -z "$apps" ]; then
  apps='./ '$(ls -d app/*/);
fi

params=""

for arg; do
  case "$arg" in *\ * )
    arg="\""${arg//\"/\'}"\"" ;;
  esac
  params+=$arg" ";
done;

if [ -z "$params" ]; then
  params="status"
fi

for i in $apps; do
  app=${i%%/};
  path=$initial/${app##/};
  cd $path;
  bn='\e[1;36m'$(basename $PWD)'\e[0m';
  echo -e $bn;
  eval $cmd $params;
  echo "";
done;
